package dev.samir.tips;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * Entity class representing a tip.
 * This class is mapped to the "tb01_tips" table in the database.
 * It contains fields for the tip ID and message.
 */
@Entity
@Table(name = "tb01_tips")
public class Tip {

	/**
	 * Unique identifier for the tip.
	 * This field is auto-generated by the database.
	 */
	@Id
	@Column(name = "tip_id")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;
	
	/**
	 * The message of the tip.
	 * This field is mapped to the "tip_message" column in the database.
	 */
	@Column(name = "tip_message")
	private String message;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getMessage() {
		return message;
	}

	public void setMessage(String message) {
		this.message = message;
	}
	
}
